### ISSUE TITLE
feature request summary

### ISSUE THREAD

**Issue by cjessett** [af3tt/bwa-u4-feature-request#1]
Adding the ability to initiate a search with the 'Enter' key significantly improves the user experience. Often, it is rare to not have that functionality. I would suggest a more appropriate name for the handler function. Instead of `getKeyboardVal`, use something like `handleKeyUp`. This will be more clear to other developers reading your code and more accurately describes its behavior.

Otherwise, you clearly and effectively communicated your proposal. Your solution is simple and I would not consider creating a new file for this functionality. Also, while this may add some lag(though not much), as you mentioned, one way to alleviate the issue would be to [debounce](https://lodash.com/docs/4.17.10#debounce) the handler.

**Comment by af3tt** [comment]
Thanks for your advice, especially about debounce! I appreciate it.
